_wandb:
    value:
        cli_version: 0.26.1
        code_path: code/run_perturb.py
        e:
            zhgcd4stef1zlk6xbq7nc6d31wj84h1x:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    macModel: Mac16,12
                    memoryGb: 16
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                args:
                    - --dataset
                    - memo_partial_pert
                    - --k
                    - "5"
                    - --rho
                    - "0.2"
                codePath: run_perturb.py
                codePathLocal: run_perturb.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "151332134912"
                email: caterina.graziani2@unisi.it
                executable: /Users/caterinagraziani/Desktop/Lavoro/RAD/.venv/bin/python
                git:
                    commit: 3847c9ade2d14539b4515a93ceb299c1e6288409
                    remote: https://github.com/EOkoyomon/wl_vs_rademacher.git
                host: MacBook-Air-di-Caterina.local
                memory:
                    total: "17179869184"
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/caterinagraziani/Desktop/Lavoro/RAD/wl_vs_rademacher/run_perturb.py
                python: CPython 3.9.6
                root: /Users/caterinagraziani/Desktop/Lavoro/RAD/wl_vs_rademacher
                startedAt: "2026-04-28T15:41:15.568296Z"
                writerId: zhgcd4stef1zlk6xbq7nc6d31wj84h1x
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 2
                - 13
                - 16
            "4": 3.9.6
            "5": 0.26.1
            "12": 0.26.1
            "13": darwin-arm64
batch_size:
    value: 16
dataset:
    value: memo_partial_pert
delta_prob:
    value: 0.95
early_stopping:
    value: 20
epochs:
    value: 500
hidden_dimension:
    value: 16
k:
    value: 5
lr:
    value: 0.0001
num_layers:
    value: 4
rho:
    value: 0.2
seed:
    value: 0
